### ISSUE TITLE
Failed to compile elm-reactor

### ISSUE THREAD

**Issue by fellz** [elm-lang/elm-reactor#105]
Hi
$: runhaskell BuildFromSource.hs master
Tried to build Elm Platform but failed with this error
```
Building elm-reactor-0.3.1...
Failed to install elm-reactor-0.3.1
Build log ( /home/goracio/code/haskell/Elm-Platform/master/logs/elm-reactor-0.3.1.log ):
[1 of 1] Compiling Main             ( dist/dist-sandbox-72ee8473/setup/setup.hs, dist/dist-sandbox-72ee8473/setup/Main.o )
Linking ./dist/dist-sandbox-72ee8473/setup/setup ...
Configuring elm-reactor-0.3.1...
Building elm-reactor-0.3.1...
Preprocessing executable 'elm-reactor' for elm-reactor-0.3.1...
[1 of 6] Compiling Paths_elm_reactor ( dist/dist-sandbox-72ee8473/build/autogen/Paths_elm_reactor.hs, dist/dist-sandbox-72ee8473/build/elm-reactor/elm-reactor-tmp/Paths_elm_reactor.o )
[2 of 6] Compiling Utils            ( backend/Utils.hs, dist/dist-sandbox-72ee8473/build/elm-reactor/elm-reactor-tmp/Utils.o )
[3 of 6] Compiling Compile          ( backend/Compile.hs, dist/dist-sandbox-72ee8473/build/elm-reactor/elm-reactor-tmp/Compile.o )

backend/Compile.hs:40:16: Not in scope: ‘<$>’

backend/Compile.hs:40:58: Not in scope: ‘<*>’

backend/Compile.hs:57:16: Not in scope: ‘<$>’

backend/Compile.hs:57:58: Not in scope: ‘<*>’
Installed elm-package-0.5
cabal: Error: some packages failed to install:
elm-reactor-0.3.1 failed during the building phase. The exception was:
ExitFailure 1

```

```
cabal --version
cabal-install version 1.22.4.0
using version 1.22.3.0 of the Cabal library 
```
```
 ghci
GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
```

**Comment by evancz** [comment]
What platform are you on? Can you use https://www.npmjs.com/package/elm to install instead?

**Comment by fellz** [comment]
@evancz it's Ubuntu 14.04

node -v 
v0.12.0
npm -v
2.5.1

```
 elm@1.4.1 postinstall /home/goracio/.nvm/versions/node/v0.12.0/lib/node_modules/elm
> node lib/install.js

  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-doc pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-make pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-package pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-reactor pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-repl pre-build test failed
```

**Comment by fellz** [comment]
@evancz so there is also error installing via npm 

```
elm-reactor
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn /home/goracio/.nvm/versions/node/v0.12.0/lib/node_modules/elm/vendor/elm-reactor ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

```

**Comment by evancz** [comment]
Why did you run `runhaskell BuildFromSource.hs master` instead of `runhaskell BuildFromSource.hs 0.15` which points to the latest stable release?

The master branches are currently in development, so they can get into a place where not everything is compatible. Do you need to get the latest stuff?

**Comment by evancz** [comment]
Also, am I correct that you are just trying to get a version of Elm installed locally?

**Comment by fellz** [comment]
@evancz Yes locally. Well 0.15 installed fine thanks.

**Comment by evancz** [comment]
Okay, sorry for the trouble! Is there anything unresolved, or can we close this issue?

**Comment by fellz** [comment]
Yea, issue can be closed, i tried examples and all is working
